//Create 
POST http://localhost:3001/Accounts/createAccount/ 
Content-Type: application/json

{

    "userName": "Bob", "dob": "1991-01-01", "email": "test@email.com", "password": "test1234", "accountRoll": "Basic"

}

###

//Create 
POST http://localhost:3001/Accounts/login/ 
Content-Type: application/json

{

    "email": "test@email.com", "password": "test1234"

}
